############################################################################
# apps/sysinfo/Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = sysinfo
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE    = $(CONFIG_SYSINFO_CMD)

MAINSRC = sysinfo_cmd.c

include $(APPDIR)/Application.mk
