############################################################################
# apps/config/Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = config
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE    = $(CONFIG_CONFIG_CMD)

MAINSRC = config_cmd.c

include $(APPDIR)/Application.mk
